### ISSUE TITLE
Alliance Crusader not in ships data.

### ISSUE THREAD

**Issue by eyeonus** [EDCD/coriolis-data#47]

**Comment by willyb321** [comment]
It is in the ships data but has not been merged to live yet.

**Comment by eyeonus** [comment]
There, clarified.

**Comment by Tromador** [comment]
From a conversation I just had with Will, his suggestion is we switch up to using the develop branch in any case.

**Comment by felixlinker** [comment]
Having a feature not on live branch is not an issue in itself. The purpose of the beta branch is to test and bundle new features. Crusader will go live soon.
