### ISSUE TITLE
Rework hardpoint data for 2.2 with official figures

### ISSUE THREAD

**Issue by cmdrmcdonald** [EDCD/coriolis-data#7]
Weapon information in coriolis-data is based on pre-2.1 assumptions and work, which included a lot of measurements for which we didn't have any baselines.  Now that we have much more information about weapons in outfitting we need to put in new information for every hardpoint (and other modules, but that's out of scope for this discussion).

As a reference, all of the data for 2.1 is available at https://docs.google.com/spreadsheets/d/1FqNfzIzA7f5e0M7xoxep-7MDpg0GrHnKm-fMhVnwSy4/edit

Current data is mixed, with combinations of damage, single shot damage, and dps for different types of weapon.  This makes comparing weapons quite difficult. and also makes causes problems with keeping primary and secondary stats in sync.

Taking an example of the class 1 gimballed pulse laser, the current coriolis-data is as follows:

```
{
  // Housekeeping
  "class": 1,
  "cost": 6600,
  "edID": 128049385,
  "eddbID": 826,
  "grp": "pl",
  "id": "18",
  "mass": 2,
  "mount": "G",
  "power": 0.39,
  "rating": "G",
  "type": "T",

  // Useful info
  "armourpen": "A",
  "damage": 2,
  "dps": 3,
  "mjdps": 7.3,
  "mjeps": 1.19,
  "rof": 4,
  "ssdam": 1.88,
  "thermload": 1
}
```

My suggestion is to change the data as follows:
- remove damage and ssdam, and use dps as the primary source of damage-dealing potential.  For periodic weapons (e.g. multicannon) the rof (rate of fire) value will be present and will allow calculation of single shot damage if required.  For continuous weapons (e.g. beam laser) there will be no rate of fire
- add an "eps" value for the energy drain of the distributor per second.  Same as above to calculate the per-shot value
- remove "thermload" and add an "hps" value for the heat generated per second.  Same as above to calculate the per-shot value
- add an "integrity" value from the new data (housekeeping, but might be useful)
- add "breachmin", "breachmax", and "breachdps" from the new data to provide breach chance as well as DPS
- remove mjdps and mjeps.  These values are the result of calculations based on old data and are no longer valid
- change "armourpen" from a rating to the numeric penetration value of the weapon

This should clean the data up and give us a consolidated way to compare different weapon classes, using dps and eps.

```
{
  // Housekeeping
  "class": 1,
  "cost": 6600,
  "edID": 128049385,
  "eddbID": 826,
  "grp": "pl",
  "id": "18",
  "integrity": 40,
  "mass": 2,
  "mount": "G",
  "power": 0.39,
  "rating": "G",
  "type": "T"

  // Useful info
  "armourpen": 20,
  "breachdps": 5.2,
  "breachmax": 0.8,
  "breachmin": 0.4,
  "dps": 6.2,
  "eps": 1.24,
  "hps": 1.2,
  "range": 3000,
  "rof": 4,
}
```

Note that there are additional parameters for other weapons (projectile speeds, shots per burst, reload times etc) but these should be able to be added to the data as required.

**Comment by cmdrmcdonald** [comment]
One thing that needs consideration is real-world DPS.  A good example of this is the fragment cannon.  A class 1 gimballed fragment cannon fires at a rate of 6 shots per second, but it only has a 3-shot clip.  So although it's nominal DPS is 72 (12 fragments x 1 damage per fragment x 6 shots per second) in reality it's closer to 13.  This may or may not be an issue here, or just something that we need to consider when displaying the data.

**Comment by Marginal** [comment]
Proposal looks good to me.

Agree that real-world DPS is a better measure than nominal DPS, and so should be displayed in the UI. So coriolis-data needs to also include clip size and reload time in order for this value to be calculated. Suggest replacing your example above with a kinetic weapon.

Also suggest "Sustained DPS" might be a good term for this in the UI. ("Sustained DPS" would ideally also factor in eps for energy weapons versus capacitor capacity, but that's getting complicated).

**Comment by cmdrmcdonald** [comment]
Here's a new-style fragment cannon as an example:

    {
      // Housekeeping
      "class": 1,
      "cost": 54720,
      "edID": 128049451,
      "eddbID": 863,
      "grp": "fc",
      "id": "21",
      "integrity": 40,
      "mass": 2,
      "mount": "G",
      "power": 0.59,
      "rating": "E",
      "type": "K",

      // Useful info
      "ammo": 90,
      "armourpen": 20,
      "breachdps": 63.4,
      "breachmax": 0.8,
      "breachmin": 0.4,
      "clip": 3,
      "dps": 71.3,
      "eps": 18.408,
      "hps": 28.32,
      "jitter": 0.5,
      "range": 2000,
      "reload": 5,
      "rof": 5.9,
      "roundspershot": 12,
      "speed": 667
    }

This is about as complicated as it gets, as it has rounds per shot as well as the usual clip/ammo/reload for ammo-based weapons.
