### ISSUE TITLE
Changes to .gitignore broke functionality downstream

### ISSUE THREAD

**Issue by eyeonus** [EDCD/coriolis-data#75]
https://github.com/eyeonus/EDDBlink-listener/issues/21#issue-447363827

TD has been using https://raw.githubusercontent.com/EDCD/coriolis-data/master/dist/index.json to get the ship info TD uses:
```
ship_id = ships[ship]['eddbID']
name = ships[ship]['properties']['name']
cost = ships[ship]['retailCost']
fdev_id = ships[ship]['edID']
```

This file, as well as thee /dist folder are now apparently being auto-generated when it is run, and is now on the .gitignore list, meaning it no longer exists at the site TD was using.

Where can I find this file now?

**Comment by willyb321** [comment]
They are currently not hosted anywhere, but if it will be useful I will look into hosting it on [beta].coriolis.io/data/index.json or similar. Let me know if that would be useful.

**Comment by Tromador** [comment]
Certainly it would be useful. Being able to continue downloading the data as we have been will remove the need for major headaches at our end.

**Comment by eyeonus** [comment]
As long as it's a stable site, that we can access, I don't care where it's stored. :)

That said, somewhere on Github would probably be better than on coriolis just because of bandwidth. I assume coriolis has a data cap, and I'd rather not increase the risk of that cap being reached, however little this might be in terms of bits transferred.

**Comment by eyeonus** [comment]
Oh, if it makes it any easier, we only need the Ship section. We never used to modules part of the json at all.

**Comment by willyb321** [comment]
In regards to bandwidth, my server is behind CF and has unlimited cap anyway. I will set something up and report back.

**Comment by eyeonus** [comment]
Cool beans.

**Comment by willyb321** [comment]
Ok, I have set up https://beta.coriolis.io/data/ for now.

Currently has index.js and index.json

Will be same version as the deployed site.

Let me know if that works for you, then I will set up prod.

**Comment by willyb321** [comment]
(also, if accessing through browser, you may need to ctrl shift r)

**Comment by eyeonus** [comment]
Thank you much, we appreciate it.

**Comment by willyb321** [comment]
FYI I have just put up https://coriolis.io/data/ (same as beta but with master branch)

/cc @eyeonus @Tromador

**Comment by eyeonus** [comment]
Thanks for the heads up.
